### ISSUE TITLE
Missing Dependencies and unwanted old GT extensions

### ISSUE THREAD

**Issue by astares** [grype/FlickrBackgrounds#2]
When I load the Baseline of the tool in Pharo11 there is some trouble - I guess due to non-loaded dependencies:

1. Unknown message #alert:

![image](https://user-images.githubusercontent.com/5980033/214877938-3e2422df-083c-448a-aaec-b9d99ec0dd62.png)

2. Missing Roassal 2 and WSUMLBilder

![image](https://user-images.githubusercontent.com/5980033/214878849-f3101147-f2aa-4c60-ba79-47021ef04cef.png)

**Comment by astares** [comment]
Maybe having the GT Tools as extensions in a package like "Flickr-Tools-GT" (also for Ethe in an own package called "Ethel-Tools-GT") with this one could separate the core / model code from the environment specific tooling support (pure Pharo or GT)

So this way in #an old environment with GT you could load the GT extensions while in pure Pharo image the baseline
could load other packages like "Flickr-Tools-GT" or "Ethel-Tools" with a Spec2 based extension approach which is now default in P10/P11

**Comment by grype** [comment]
Thanks, @astares. Both issues should have been resolved. As far as breaking down packages - Ethel's tools are now in a separate package and that package doesn't get loaded implicitly. I also need to refresh those tools for pharo10+ =/
